

CREATE TABLE KORISNIK
(
  KorisnickoIme Varchar(20) NOT NULL,
  Sifra Varchar(60) NOT NULL,
  ImePrezime Varchar(40) NOT NULL,
  Mejl Varchar(40) NOT NULL,
  DatumRodjenja Date NOT NULL,
  Tip Char(1) NOT NULL,
  Status Char(1) NOT NULL
)
;

ALTER TABLE KORISNIK ADD PRIMARY KEY (KorisnickoIme)
;

-- Table TIP_SPRAVE

CREATE TABLE TIP_SPRAVE
(
  IdTip Int NOT NULL AUTO_INCREMENT,
  Naziv Varchar(30) NOT NULL,
  Opis Varchar(200),
  Slika Longblob NOT NULL,
  PRIMARY KEY (IdTip)
)
;

-- Table SPRAVA

CREATE TABLE SPRAVA
(
  IdSpr Int NOT NULL AUTO_INCREMENT,
  IdTip Int,
  Aktivna Bool NOT NULL,
  PRIMARY KEY (IdSpr)
)
;

CREATE INDEX IX_Relationship1 ON SPRAVA (IdTip)
;

-- Table TERMIN

CREATE TABLE TERMIN
(
  IdTer Int NOT NULL AUTO_INCREMENT,
  Datum Date NOT NULL,
  Vreme Time NOT NULL,
  Status Char(1) NOT NULL,
  KorisnickoIme Varchar(20),
  PRIMARY KEY (IdTer)
)
;

CREATE INDEX IX_Relationship5 ON TERMIN (KorisnickoIme)
;

-- Table REZERVACIJA

CREATE TABLE REZERVACIJA
(
  IdRez Int NOT NULL AUTO_INCREMENT,
  IdTer Int,
  IdSpr Int,
  PRIMARY KEY (IdRez)
)
;

CREATE INDEX IX_Relationship3 ON REZERVACIJA (IdTer)
;

CREATE INDEX IX_Relationship4 ON REZERVACIJA (IdSpr)
;

-- Table GRUPA_MISICA

CREATE TABLE GRUPA_MISICA
(
  IdGru Int NOT NULL AUTO_INCREMENT,
  Naziv Varchar(20) NOT NULL,
  PRIMARY KEY (IdGru)
)
;

-- Table POGODJENA_GRUPA_MISICA

CREATE TABLE POGODJENA_GRUPA_MISICA
(
  IdTip Int NOT NULL,
  IdGru Int NOT NULL,
  Jacina Int NOT NULL
)
;

ALTER TABLE POGODJENA_GRUPA_MISICA ADD PRIMARY KEY (IdTip, IdGru)
;

-- Table ZAHTEV

CREATE TABLE ZAHTEV
(
  IdZah Int NOT NULL AUTO_INCREMENT,
  Status Char(1) NOT NULL,
  KorisnickoIme Varchar(20),
  Tip Char(1) NOT NULL,
  PRIMARY KEY (IdZah)
)
;

CREATE INDEX IX_Relationship8 ON ZAHTEV (KorisnickoIme)
;

-- Create foreign keys (relationships) section -------------------------------------------------

ALTER TABLE SPRAVA ADD CONSTRAINT je_tipa FOREIGN KEY (IdTip) REFERENCES TIP_SPRAVE (IdTip) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE REZERVACIJA ADD CONSTRAINT za_termin FOREIGN KEY (IdTer) REFERENCES TERMIN (IdTer) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE REZERVACIJA ADD CONSTRAINT rezervisane FOREIGN KEY (IdSpr) REFERENCES SPRAVA (IdSpr) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE TERMIN ADD CONSTRAINT zakazao FOREIGN KEY (KorisnickoIme) REFERENCES KORISNIK (KorisnickoIme) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE POGODJENA_GRUPA_MISICA ADD CONSTRAINT pogadja FOREIGN KEY (IdTip) REFERENCES TIP_SPRAVE (IdTip) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE POGODJENA_GRUPA_MISICA ADD CONSTRAINT je_pogodjena FOREIGN KEY (IdGru) REFERENCES GRUPA_MISICA (IdGru) ON DELETE RESTRICT ON UPDATE RESTRICT
;

ALTER TABLE ZAHTEV ADD CONSTRAINT zahteva FOREIGN KEY (KorisnickoIme) REFERENCES KORISNIK (KorisnickoIme) ON DELETE SET NULL ON UPDATE RESTRICT
;


